"""empty message

Revision ID: 984ec38fcb4a
Revises: f72fa55efc94
Create Date: 2021-08-17 23:25:26.215976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '984ec38fcb4a'
down_revision = 'f72fa55efc94'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Integer(), nullable=False))
    op.drop_column('users', 'roll')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roll', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
